### ISSUE TITLE
Crashed while send sms from android.

### ISSUE THREAD

**Issue by sooryaraj** [akshaydoshi2/flutter_sim_data#1]
Android V-14 got crashed while sending sms

D/CompatibilityChangeReporter(23610): Compat change id reported: 160794467; UID 10494; state: ENABLED
E/MethodChannel#sim_data(23610): Failed to handle method call
E/MethodChannel#sim_data(23610): java.lang.SecurityException: app.myapp.com: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/MethodChannel#sim_data(23610): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/MethodChannel#sim_data(23610): 	at android.os.Parcel.createException(Parcel.java:3041)
E/MethodChannel#sim_data(23610): 	at android.os.Parcel.readException(Parcel.java:3024)
E/MethodChannel#sim_data(23610): 	at android.os.Parcel.readException(Parcel.java:2966)
E/MethodChannel#sim_data(23610): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6205)
E/MethodChannel#sim_data(23610): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
E/MethodChannel#sim_data(23610): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
E/MethodChannel#sim_data(23610): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
E/MethodChannel#sim_data(23610): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
E/MethodChannel#sim_data(23610): 	at com.example.sim_data.SimDataPlugin.sendSMS(SimDataPlugin.java:188)
E/MethodChannel#sim_data(23610): 	at com.example.sim_data.SimDataPlugin.onMethodCall(SimDataPlugin.java:91)
E/MethodChannel#sim_data(23610): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#sim_data(23610): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#sim_data(23610): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#sim_data(23610): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
E/MethodChannel#sim_data(23610): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#sim_data(23610): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#sim_data(23610): 	at android.os.Looper.loopOnce(Looper.java:222)
E/MethodChannel#sim_data(23610): 	at android.os.Looper.loop(Looper.java:314)
E/MethodChannel#sim_data(23610): 	at android.app.ActivityThread.main(ActivityThread.java:8680)
E/MethodChannel#sim_data(23610): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#sim_data(23610): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
E/MethodChannel#sim_data(23610): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
E/MethodChannel#sim_data(23610): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#sim_data(23610): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14715)
E/MethodChannel#sim_data(23610): 	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12225)
E/MethodChannel#sim_data(23610): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3194)
E/MethodChannel#sim_data(23610): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2895)
E/MethodChannel#sim_data(23610): 	at android.os.Binder.execTransactInternal(Binder.java:1346)
E/MethodChannel#sim_data(23610): 
E/flutter (23610): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, app.myapp.com: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts, null, java.lang.SecurityException: app.myapp.com: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/flutter (23610): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/flutter (23610): 	at android.os.Parcel.createException(Parcel.java:3041)
E/flutter (23610): 	at android.os.Parcel.readException(Parcel.java:3024)
E/flutter (23610): 	at android.os.Parcel.readException(Parcel.java:2966)
E/flutter (23610): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6205)
E/flutter (23610): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
E/flutter (23610): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
E/flutter (23610): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
E/flutter (23610): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
E/flutter (23610): 	at com.example.sim_data.SimDataPlugin.sendSMS(SimDataPlugin.java:188)
E/flutter (23610): 	at com.example.sim_data.SimDataPlugin.onMethodCall(SimDataPlugin.java:91)
E/flutter (23610): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter (23610): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter (23610): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (23610): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
E/flutter (23610): 	at android.os.Handler.handleCallback(Handler.java:958)
E/flutter (23610): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (23610): 	at android.os.Looper.loopOnce(Looper.java:222)
E/flutter (23610): 	at android.os.Looper.loop(Looper.java:314)
E/flutter (23610): 	at android.app.ActivityThread.main(ActivityThread.java:8680)
E/flutter (23610): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (23610): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
E/flutter (23610): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
E/flutter (23610): Caused by: android.os.RemoteException: Remote stack trace:
E/flutter (23610): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14715)
E/flutter (23610): 	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12225)
E/flutter (23610): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3194)
E/flutter (23610): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2895)
E/flutter (23610): 	at android.os.Binder.execTransactInternal(Binder.java:1346)
E/flutter (23610): 
E/flutter (23610): )
E/flutter (23610): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (23610): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (23610): <asynchronous suspension>
E/flutter (23610): #2      MethodChannelSimData.sendSMS (package:flutter_sim_data/sim_data_method_channel.dart:30:12)
E/flutter (23610): <asynchronous suspension>
E/flutter (23610): #3      SimData.sendSMS (package:flutter_sim_data/sim_data.dart:45:12)
E/flutter (23610): <asynchronous suspension>
E/flutter (23610):

**Comment by akshaydoshi2** [comment]
Fixed in `1.0.5`
Tested on Samsung Galaxy F34 5G running Android 14

**Comment by sooryaraj** [comment]
Thanks it's working
